### ISSUE TITLE
missing json file in the repo

### ISSUE THREAD

**Issue by run4w4y** [vizanto/nixlixhx#1]
Hello! I've tried using your repo to get haxe4 working with nix, but, unfortunately, when i try to run `nix-shell shell.nix` in the root dir of the repo, i get the following error: `error: opening file '/home/adachi/nixlixhx/nixpkgs-overlay/haxe-4.0.3.json': No such file or directory`. Am I doing something wrong?

**Comment by vizanto** [comment]
You are not :)  Please try again

**Comment by vizanto** [comment]
I see you already got 4.0.5 (binary) working! Let me update the JSON.

**Comment by run4w4y** [comment]
Thank you!
